default:
  autoload:
    '': %paths.base%/../src/tests/bootstrap/
  suites:

    registerAccount:
      paths:
        - %paths.base%/../src/tests/integration/features/Account/RegisterAccount
      contexts:
        - Nextbike\Context\Account\RegisterAccount\RegisterAccountContext

    loginAccount:
      paths:
        - %paths.base%/../src/tests/integration/features/Account/LoginAccount
      contexts:
        - Nextbike\Context\Account\LoginAccount\LoginAccountContext

    listAccount:
      paths:
        - %paths.base%/../src/tests/integration/features/Account/ListAccount
      contexts:
        - Nextbike\Context\Account\ListAccount\ListAccountContext

    getBikeState:
      paths:
        - %paths.base%/../src/tests/integration/features/Bike/GetBikeStateContext
      contexts:
        - Nextbike\Context\Bike\GetBikeState\GetBikeStateContext


    updateCustomerDataAccount:
          paths:
            - %paths.base%/../src/tests/integration/features/Account/UpdateCustomerData
          contexts:
            - Nextbike\Context\Account\UpdateCustomerData\UpdateCustomerDataContext

    tariffs:
          paths:
            - %paths.base%/../src/tests/integration/features/Tariffs/Tariffs
          contexts:
            - Nextbike\Context\Tariffs\Tariffs\TariffsContext

    rentBike:
      paths:
        - %paths.base%/../src/tests/integration/features/Bike/Rent
      contexts:
        - Nextbike\Context\Bike\RentContext\RentContext

    singleTariff:
              paths:
                - %paths.base%/../src/tests/integration/features/Tariffs/SingleTariff
              contexts:
                - Nextbike\Context\Tariffs\SingleTariff\SingleTariffContext

    singleTariffbyCode:
                  paths:
                    - %paths.base%/../src/tests/integration/features/Tariffs/SingleTariffbyCode
                  contexts:
                    - Nextbike\Context\Tariffs\SingleTariff\SingleTariffByCodeContext

    AbortRentalBike:
      paths:
        - %paths.base%/../src/tests/integration/features/Bike/AbortRental
      contexts:
        - Nextbike\Context\Bike\AbortRentalContext\AbortRentalContext