default:
  autoload:
    '': %paths.base%/../src/tests/bootstrap/
  suites:

    registerAccount:
      paths:
        - %paths.base%/../src/tests/integration/features/Account/RegisterAccount
      contexts:
        - Nextbike\Context\Account\RegisterAccount\RegisterAccountContext

    loginAccount:
      paths:
        - %paths.base%/../src/tests/integration/features/Account/LoginAccount
      contexts:
        - Nextbike\Context\Account\LoginAccount\LoginAccountContext

    listAccount:
      paths:
        - %paths.base%/../src/tests/integration/features/Account/ListAccount
      contexts:
        - Nextbike\Context\Account\ListAccount\ListAccountContext


    getBikeState:
      paths:
        - %paths.base%/../src/tests/integration/features/Bike/GetBikeState
      contexts:
        - Nextbike\Context\Bike\GetBikeState\GetBikeStateContext







